
const fs = require('fs');
const path = require('path');

// 입력 파일과 출력 파일 경로 정의
const inputFilePath = path.join(__dirname, '../src/features/lease/floorPlanLayouts.ts');
const outputDirPath = path.join(__dirname, '../src/data');
const outputFilePath = path.join(outputDirPath, 'editableFloorPlanLayouts.ts');

// 1. 입력 파일 읽기
fs.readFile(inputFilePath, 'utf8', (err, data) => {
  if (err) {
    console.error("Error reading floorPlanLayouts.ts:", err);
    return;
  }

  // 2. 정규식을 사용하여 floorPlanLayouts 객체 부분만 추출
  const match = data.match(/export const floorPlanLayouts: { \[key: string\]: UnitLayout } = ({[\s\S]*?});/);
  if (!match) {
    console.error("Could not find floorPlanLayouts object in the input file.");
    return;
  }

  // 3. eval을 사용하여 추출된 문자열을 JavaScript 객체로 변환
  let floorPlanLayouts;
  try {
    floorPlanLayouts = eval('(' + match[1] + ')');
  } catch (e) {
    console.error("Failed to parse floorPlanLayouts object:", e);
    return;
  }

  // 4. path를 points 배열로 변환하고 층별로 그룹화
  const editableLayoutsByFloor = Object.entries(floorPlanLayouts).reduce((acc, [id, layout]) => {
    const floorMatch = id.match(/-(\dF)-/);
    if (!floorMatch) return acc;
    
    const floor = `${floorMatch[1].charAt(0)}층`; // "1F" -> "1층"

    const points = layout.path
      .replace(/[M|L|Z]/g, '') // "M", "L", "Z" 문자 제거
      .trim()
      .split(' ') // 공백으로 분리
      .filter(p => p.includes(',')) // "x,y" 형태의 쌍만 필터링
      .map(pair => {
        const [x, y] = pair.split(',');
        return { x: parseInt(x, 10), y: parseInt(y, 10) };
      });

    if (!acc[floor]) {
      acc[floor] = { floor: floor, layout: [] };
    }

    acc[floor].layout.push({ id, points });

    return acc;
  }, {});

  const finalLayouts = Object.values(editableLayoutsByFloor);

  // 5. 결과를 TypeScript 파일 형식으로 포맷팅
  const outputContent = `
// This file is generated automatically by scripts/convertPathData.js
// Do not edit this file manually.

import { EditableFloorLayout } from '../types';

export const editableFloorPlanLayouts: EditableFloorLayout[] = ${JSON.stringify(finalLayouts, null, 2)};
`;

  // 6. 출력 디렉터리가 없으면 생성
  if (!fs.existsSync(outputDirPath)) {
    fs.mkdirSync(outputDirPath, { recursive: true });
  }

  // 7. 결과 파일 작성
  fs.writeFile(outputFilePath, outputContent, 'utf8', (err) => {
    if (err) {
      console.error("Error writing editableFloorPlanLayouts.ts:", err);
      return;
    }
    console.log('Successfully converted path data and created editableFloorPlanLayouts.ts');
  });
});
